server:
 port: 5001
mongo:
 uri: mongodb+srv://ior-admin:IhbPJ6IXoNFqOEfi@ior.y9m2w.gcp.mongodb.net/test
websocket:
 enable: false
 port: 9000
kuzzle:
 enable: false
 port: 7505
kafka:
 enable: false
 port: 31001
zookeeper:
 enable: false
 servers: localhost:2181