apiVersion: v1
kind: Namespace
metadata:
  name: ior

---

apiVersion: v1
kind: Service
metadata:
  name: ior-exporter
  namespace: ior
spec:
  selector:
    app: ior-worker
  ports:
  - protocol: TCP
    name: http-port
    port: 8080
    nodePort: 31000
  - protocol: TCP
    name: socket-port
    port: 8000
    nodePort: 31001
  type: NodePort
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ior-deployment
  namespace: ior
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ior-worker
  template:
    metadata:
      labels:
        app: ior-worker
    spec:
      containers:
      - name: ior-worker
        image: mayank31313/ior:latest
        imagePullPolicy: Always
        env:
          - name: DATABASE_URL
            value: jdbc:mysql://192.168.46.12:3306/iorproject
          - name: DATABASE_USER
            value: ior
          - name: DATABASE_PASSWORD
            value: abcdF54321@
          - name: ZOOKEEPER_SERVERS
            value: 192.168.46.12:31452
          - name: JDBC_DRIVER
            value: com.mysql.jdbc.Driver
          
        ports:
        - containerPort: 8080
        - containerPort: 8000